<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ABOUT_TITLE' => 'O stronie',
    'BUTTON_CREATE' => 'Stwórz',
    'BUTTON_DELETE' => 'Usuń',
    'BUTTON_LOGIN' => 'Zaloguj',
    'BUTTON_RECAP_CREATE' => 'Stwórz streszczenie',
    'BUTTON_SAVE' => 'Zapisz',
    'BUTTON_SEND' => 'Wyślij',
    'BUTTON_SIGNUP' => 'Zarejestruj',
    'BUTTON_STORY_CREATE' => 'Stwórz Historię',
    'BUTTON_STORY_PARAMETER_CREATE' => 'Dodaj parametr Historii',
    'BUTTON_SUBMIT' => 'Wyślij',
    'BUTTON_UPDATE' => 'Zmień',
    'BUTTON_USER_CREATE' => 'Zarejestruj użytkownika',
    'CONTACT_TITLE' => 'Kontakt',
    'Create' => '',
    'LABEL_CONTENT' => 'Treść',
    'LABEL_UPDATE' => 'Edycja',
    'LOGIN_TITLE' => 'Logowanie',
    'Login' => '',
    'QUESTION_DELETE' => 'Usunąć obiekt?',
    'RECAP_CREATE_TITLE' => 'Nowe streszczenie',
    'RECAP_DATA' => 'Dane',
    'RECAP_ID' => 'ID streszczenia',
    'RECAP_KEY' => 'Klucz',
    'RECAP_NAME' => 'Tytuł',
    'RECAP_TIME' => 'Czas',
    'RECAP_TITLE_INDEX' => 'Streszczenia',
    'RECAP_TITLE_UPDATE' => 'Edycja streszczenia',
    'STORY_BASICS_HEADER' => 'Dane podstawowe',
    'STORY_DATA' => 'Dane',
    'STORY_HEADER_LONG' => 'Długi opis',
    'STORY_HEADER_SHORT' => 'Krótki opis',
    'STORY_ID' => 'ID Historii',
    'STORY_KEY' => 'Klucz',
    'STORY_LONG' => 'Długi opis',
    'STORY_NAME' => 'Tytuł',
    'STORY_PARAMETERS' => 'Parametry historii',
    'STORY_PARAMETER_CODE' => 'Kod',
    'STORY_PARAMETER_CONTENT' => 'Treść',
    'STORY_PARAMETER_ID' => 'ID parametru historii',
    'STORY_PARAMETER_VISIBILITY' => 'Widoczność',
    'STORY_SHORT' => 'Krótki opis',
    'STORY_TITLE_CREATE' => 'Stwórz historię',
    'STORY_TITLE_INDEX' => 'Historie',
    'STORY_TITLE_UPDATE' => 'Zmiany w Historii',
    'Stories' => 'Historie',
    'TITLE_LOGIN' => 'Logowanie',
    'TITLE_PASSWORD_RESET' => 'Reset hasła',
    'TITLE_PASSWORD_RESET_REQUEST' => 'Żądanie resetu hasła',
    'TITLE_SIGNUP' => 'Rejestracja',
    'Update' => 'Zmień',
    'View' => 'Podgląd',
];
