<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'BUTTON_CREATE' => 'Stwórz',
    'BUTTON_DELETE' => 'Usuń',
    'BUTTON_LOGIN' => 'Zaloguj',
    'BUTTON_RECAP_CREATE' => 'Stwórz streszczenie',
    'BUTTON_STORY_CREATE' => 'Stwórz Historię',
    'BUTTON_UPDATE' => 'Zmień',
    'Create' => '',
    'Create Recap' => '',
    'Delete' => '',
    'MESSAGE_DELETE_CONFIRMATION' => 'Czy chcesz usunąć ten obiekt?',
    'RECAP_DATA' => 'Dane',
    'RECAP_ID' => 'ID streszczenia',
    'RECAP_KEY' => 'Klucz',
    'RECAP_NAME' => 'Tytuł',
    'RECAP_TIME' => 'Czas',
    'Recaps' => '',
    'STORY_DATA' => 'Dane',
    'STORY_ID' => 'ID Historii',
    'STORY_KEY' => 'Klucz',
    'STORY_LONG' => 'Długi opis',
    'STORY_NAME' => 'Tytuł',
    'STORY_PARAMETER_CODE' => 'Kod',
    'STORY_PARAMETER_CONTENT' => 'Treść',
    'STORY_PARAMETER_ID' => 'ID parametru historii',
    'STORY_PARAMETER_VISIBILITY' => 'Widoczność',
    'STORY_SHORT' => 'Krótki opis',
    'Stories' => '',
    'TITLE_LOGIN' => 'Logowanie',
    'TITLE_RECAP' => 'Streszczenia',
    'TITLE_RECAP {modelClass}: ' => 'Streszczenie {modelClass}: ',
    'TITLE_STORIES' => 'Historie',
    'TITLE_STORY_CREATE' => '',
    'TITLE_UPDATE {modelClass}: ' => 'Zmień {modelClass}: ',
    'Update' => '',
];
