<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NO_DATA' => 'Brak danych',
    'PERSON_REPUTATIONS_TAB' => 'Reputacje',
    'REPUTATION_BALANCE' => 'Wartość<br>bieżąca',
    'REPUTATION_BALANCE_RANGE' => 'Zakres<br>wartości',
    'REPUTATION_DICE' => 'Kości',
    'REPUTATION_NAME' => 'Nazwa reputacji',
    'REPUTATION_RECOGNITION_DICE' => 'Sława',
    'REPUTATION_RECOGNITION_DICE_TITLE' => 'Liczba kości rzucana przy próbie rozpoznania postaci przez osobę powiązaną z daną Reputacją',
    'REPUTATION_REPUTATION_DICE_TITLE' => 'Kości do użytku gracza i MG do wspierania bądź zakłócania interakcji społecznych',
];
