<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CHARACTER_REPUTATIONS_TAB' => 'Reputacje',
    'CHARACTER_REPUTATION_EVENTS_TAB' => 'Historia reputacji',
    'CHARACTER_SHEET_TAB_TITLE_NEEDED' => '[nie znaleziono nagłówka]',
    'EXTERNAL_DATA_CODE' => 'Kod identyfikacyjny',
    'EXTERNAL_DATA_DATA' => 'Dane',
    'EXTERNAL_DATA_FORMAT_CONTENT' => '<ul>
<li>Komponent najwyższego stopnia musi być tablicą</li>
<li>Każda zakładka jest reprezentowana przez osobny obiekt z wymaganymi polami: "title" i "data"</li>
<li>Każde pole "title" to string</li>
<li>Każde pole "data" to tablica obiektów</li>
<li>Każdy obiekt danych musi mieć:
<ul>
<li>pole "type" z wartością "table" lub "text"</li>
<li>pole treści: "rows" dla tablic, "text" dla tekstu</li>
</ul>
</li>
<li>Każdy obiekt danych może mieć pole "title" jako string</li>
<li>Każdy obiekt danych może mieć pole "size" jako string, opisujące rozmiar kolumny; opcje to: smallest, smaller, small, medium, large, larger, largest lub liczba między 1 a 12 włącznie, opisująca rozmiar wg bootstrapa</li>
<li>Każdy obiekt tekstowy to string; może to być HTML</li>
<li>Każdy obiekt "rows" to tablica (opisująca wiersze) tablic obiektów (opisujących komórki)
<ul>
<li>Każdy obiekt opisujący komórkę musi mieć pole "data", zawierające treść</li>
<li>Każdy obiekt opisujący komórkę może mieć pole "title", zawierające title text</li>
<li>Każdy obiekt opisujący komórkę może mieć pole "class", zawierające klasy CSS </li>
</ul>
</li>
</ul>',
    'EXTERNAL_DATA_FORMAT_TITLE' => 'Wymagania co do formatu JSON-a',
    'EXTERNAL_DATA_ID' => 'ID',
    'EXTERNAL_DATA_LOAD_ERROR_JSON' => 'Ładowanie zewnętrznych danych nieudane - błąd JSON-a',
    'EXTERNAL_DATA_LOAD_ERROR_PARTITION {errors}' => 'Ładowanie zewnętrznych danych częściowo nieudane - błędy w pakietach: {errors}',
    'EXTERNAL_DATA_LOAD_ERROR_SAVE' => 'Ładowanie zewnętrznych danych nieudane - błąd zapisu',
    'EXTERNAL_DATA_LOAD_SUCCESS' => 'Ładowanie zewnętrznych danych udane',
    'EXTERNAL_DATA_MALFORMED_ARRAY' => 'Ładowanie zewnętrznych danych nieudane - wadliwy format tablicy',
    'EXTERNAL_DATA_PACK_CLASS' => 'Klasa',
    'EXTERNAL_DATA_PACK_ID' => 'ID pakietu',
    'GROUP_REPUTATIONS_TAB' => 'Reputacje',
    'GROUP_REPUTATION_EVENTS_TAB' => 'Historia reputacji',
    'NO_DATA' => 'Brak danych dla obiektu',
    'REPUTATION_BALANCE' => 'Wartość<br>bieżąca',
    'REPUTATION_BALANCE_RANGE' => 'Zakres<br>wartości',
    'REPUTATION_CHANGE' => 'Zmiana',
    'REPUTATION_DICE' => 'Kości',
    'REPUTATION_EVENT' => 'Wydarzenie',
    'REPUTATION_EVENT_NOTE' => '<b>Uwaga:</b> To jest tymczasowe rozwiązanie, służące prezentacji danych w najprostszej możliwej postaci dopóki nie powstanie coś sensowniejszego do obsługi wydarzeń.',
    'REPUTATION_NAME' => 'Nazwa<br>reputacji',
    'REPUTATION_NOTES' => 'Notes',
    'REPUTATION_RECOGNITION_DICE' => 'Sława',
    'REPUTATION_RECOGNITION_DICE_TITLE' => 'Liczba kości rzucana przy próbie rozpoznania postaci przez osobę powiązaną z daną Reputacją',
    'REPUTATION_REPUTATION_DICE_TITLE' => 'Kości do użytku gracza i MG do wspierania bądź zakłócania interakcji społecznych',
    'REPUTATION_WHEN' => 'Kiedy?',
];
