<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'GREETING' => 'Dzień dobry',
    'INVITATION_EMAIL_SUBJECT' => 'Zaproszenie do założenia konta',
    'RESET_PASSWORD_BODY' => 'Poniższy link umożliwia reset hasła:',
    'SIGNATURE_HTML_SIMPLE' => '<p>Mail został wygenerowany przez Centrum RPG</p>',
    'SIGNATURE_HTML_WITH_LINK' => '<p>Mail został wygenerowany przez <a href="{link}">Centrum RPG</a></p>',
    'SIGNATURE_TEXT_SIMPLE' => 'Mail został wygenerowany przez Centrum RPG',
    'SIGNATURE_TEXT_WITH_LINK' => 'Mail został wygenerowany przez Centrum RPG: {link}',
    'USER_INVITATION_BODY_TEXT' => 'Link umożliwiający założenie konta:',
    'USER_INVITATION_EXPIRATION_WARNING {when}' => 'Ważność zaproszenia kończy się {when}. Jeżeli termin ten już upłynął, skontaktuj się z nadawcą.',
];
