<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ABOUT_TITLE' => 'About',
    'QUESTION_DELETE' => 'Are you sure you want to delete this item?',
    'BUTTON_CREATE' => 'Create',
    'BUTTON_DELETE' => 'Delete',
    'BUTTON_LOGIN' => 'Login',
    'BUTTON_RECAP_CREATE' => 'Create recap',
    'BUTTON_SAVE' => 'Save',
    'BUTTON_SEND' => 'Send',
    'BUTTON_SIGNUP' => 'Sign up',
    'BUTTON_STORY_CREATE' => 'Create story',
    'BUTTON_SUBMIT' => 'Submit',
    'BUTTON_UPDATE' => 'Update',
    'BUTTON_USER_CREATE' => 'Create user',
    'CONTACT_TITLE' => 'Contact',
    'LABEL_UPDATE' => 'Edit',
    'LOGIN_TITLE' => 'Login',
    'MESSAGE_DELETE_CONFIRMATION' => 'Are you sure you want to delete this item?',
    'RECAP_CREATE_TITLE' => 'Create recap',
    'RECAP_DATA' => 'Data',
    'RECAP_ID' => 'Recap ID',
    'RECAP_KEY' => 'Key',
    'RECAP_NAME' => 'Recap title',
    'RECAP_TIME' => 'Time',
    'RECAP_TITLE_INDEX' => 'Recaps',
    'RECAP_TITLE_UPDATE' => 'Recap edit',
    'STORY_DATA' => 'Data',
    'STORY_ID' => 'Story ID',
    'STORY_KEY' => 'Key',
    'STORY_LONG' => 'Long description',
    'STORY_NAME' => 'Story title',
    'STORY_PARAMETER_CODE' => 'Code',
    'STORY_PARAMETER_CONTENT' => 'Content',
    'STORY_PARAMETER_ID' => 'Story parameter ID',
    'STORY_PARAMETER_VISIBILITY' => 'Visibility',
    'STORY_SHORT' => 'Short description',
    'STORY_TITLE_CREATE' => 'Create story',
    'STORY_TITLE_INDEX' => 'Stories',
    'STORY_TITLE_UPDATE' => 'Edit story',
    'STORY_TITLE_UPDATE {modelClass}: ' => 'Update {modelClass}: ',
    'Stories' => 'Stories',
    'TITLE_LOGIN' => 'Login',
    'TITLE_PASSWORD_RESET' => 'Password reset',
    'TITLE_PASSWORD_RESET_REQUEST' => 'Request password reset',
    'TITLE_SIGNUP' => 'Sign up',
    'Update' => '',
];
