<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'BUTTON_CREATE' => 'Create',
    'BUTTON_DELETE' => 'Delete',
    'BUTTON_LOGIN' => 'Login',
    'BUTTON_RECAP_CREATE' => 'Create recap',
    'BUTTON_SAVE' => 'Save',
    'BUTTON_SEND' => 'Send',
    'BUTTON_SIGNUP' => 'Sign up',
    'BUTTON_STORY_CREATE' => 'Create story',
    'BUTTON_UPDATE' => 'Update',
    'Create' => '',
    'Create Recap' => '',
    'Delete' => '',
    'MESSAGE_DELETE_CONFIRMATION' => 'Are you sure you want to delete this item?',
    'RECAP_DATA' => 'Data',
    'RECAP_ID' => 'Recap ID',
    'RECAP_KEY' => 'Key',
    'RECAP_NAME' => 'Recap title',
    'RECAP_TIME' => 'Time',
    'Recaps' => '',
    'STORY_DATA' => 'Data',
    'STORY_ID' => 'Story ID',
    'STORY_KEY' => 'Key',
    'STORY_LONG' => 'Long description',
    'STORY_NAME' => 'Story title',
    'STORY_PARAMETER_CODE' => 'Code',
    'STORY_PARAMETER_CONTENT' => 'Content',
    'STORY_PARAMETER_ID' => 'Story parameter ID',
    'STORY_PARAMETER_VISIBILITY' => 'Visibility',
    'STORY_SHORT' => 'Short description',
    'Stories' => 'Stories',
    'TITLE_LOGIN' => 'Login',
    'TITLE_PASSWORD_RESET' => 'Password reset',
    'TITLE_RECAP' => 'Recaps',
    'TITLE_RECAP {modelClass}: ' => 'Recap {modelClass}: ',
    'TITLE_SIGNUP' => 'Sign up',
    'TITLE_STORIES' => 'Stories',
    'TITLE_STORY_CREATE' => 'Create story',
    'TITLE_UPDATE {modelClass}: ' => 'Update {modelClass}: ',
    'Update' => '',
];
