<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BUTTON_CREATE' => 'Create',
    'BUTTON_DELETE' => 'Delete',
    'BUTTON_LOGIN' => 'Login',
    'BUTTON_RECAP_CREATE' => 'Create recap',
    'BUTTON_STORY_CREATE' => 'Create story',
    'BUTTON_UPDATE' => 'Update',
    'Code' => 'Code',
    'Content' => 'Content',
    'Data' => 'Data',
    'Key' => 'Key',
    'Long' => 'Long',
    'MESSAGE_DELETE_CONFIRMATION' => 'Are you sure you want to delete this item?',
    'Name' => 'Name',
    'Recap ID' => 'Recap ID',
    'Short' => 'Short',
    'Story ID' => 'Story ID',
    'Story Parameter ID' => 'Story Parameter ID',
    'TITLE_LOGIN' => 'Login',
    'TITLE_RECAP' => 'Recaps',
    'TITLE_RECAP {modelClass}: ' => 'Recap {modelClass}: ',
    'TITLE_STORIES' => 'Stories',
    'TITLE_STORY_CREATE' => 'Create story',
    'TITLE_UPDATE {modelClass}: ' => 'Update {modelClass}: ',
    'Time' => 'Time',
    'Visibility' => 'Visibility',
];
