<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CHARACTER_REPUTATIONS_TAB' => 'Reputations',
    'CHARACTER_REPUTATION_EVENTS_TAB' => 'Reputation history',
    'EXTERNAL_DATA_CODE' => 'Identification code',
    'EXTERNAL_DATA_DATA' => 'Data',
    'EXTERNAL_DATA_ID' => 'ID',
    'EXTERNAL_DATA_LOAD_ERROR_JSON' => 'Loading operation failed - JSON issue',
    'EXTERNAL_DATA_LOAD_ERROR_PARTITION {errors}' => 'Loading operation partially failed - unable to partition data. Problems found in {errors} packs.',
    'EXTERNAL_DATA_LOAD_ERROR_SAVE' => 'Loading operation failed - save failed',
    'EXTERNAL_DATA_LOAD_SUCCESS' => 'Loading operation successful',
    'EXTERNAL_DATA_MALFORMED_ARRAY' => 'Loading operation failed - malformed array',
    'EXTERNAL_DATA_PACK_CLASS' => 'Class',
    'EXTERNAL_DATA_PACK_ID' => 'Pack ID',
    'NO_DATA' => 'No data for this object found',
    'REPUTATION_BALANCE' => 'Current<br>balance',
    'REPUTATION_BALANCE_RANGE' => 'Balance<br>range',
    'REPUTATION_CHANGE' => 'Change',
    'REPUTATION_DICE' => 'Dice',
    'REPUTATION_EVENT' => 'Event',
    'REPUTATION_EVENT_NOTE' => '<b>Warning: </b> This is a temporary solution, intended to display data in their simplest form before a better way to display events can be found and implemented.',
    'REPUTATION_NAME' => 'Name of the reputation',
    'REPUTATION_NOTES' => 'notes',
    'REPUTATION_RECOGNITION_DICE' => 'Recognition',
    'REPUTATION_RECOGNITION_DICE_TITLE' => 'Number of dice used in recognition attempt rolled by person associated with the reputation',
    'REPUTATION_REPUTATION_DICE_TITLE' => 'Dice available for player and GM use for improving or disrupting social situations',
    'REPUTATION_WHEN' => 'When?',
];
