<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NO_DATA' => 'No data available',
    'PERSON_REPUTATIONS_TAB' => 'Reputations',
    'REPUTATION_BALANCE' => 'Current<br>balance',
    'REPUTATION_BALANCE_RANGE' => 'Balance<br>range',
    'REPUTATION_DICE' => 'Dice',
    'REPUTATION_NAME' => 'Name of the reputation',
    'REPUTATION_RECOGNITION_DICE' => 'Recognition',
    'REPUTATION_RECOGNITION_DICE_TITLE' => 'Number of dice used in recognition attempt rolled by person associated with the reputation',
    'REPUTATION_REPUTATION_DICE_TITLE' => 'Dice available for player and GM use for improving or disrupting social situations',
];
