<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'GREETING' => 'Hello',
    'INVITATION_EMAIL_SUBJECT' => 'Invitation for account creation',
    'RESET_PASSWORD_BODY' => 'Follow the link below to reset your password:',
    'SIGNATURE_HTML' => '<p>This message has been generated by the RPG hub</p>',
    'SIGNATURE_TEXT' => 'This message has been generated by the RPG hub',
    'USER_INVITATION_BODY_TEXT' => 'Follow the link below to set up your account:',
    'USER_INVITATION_EXPIRATION_WARNING {when}' => 'This invitation expires {when}. If you missed that deadline, please contact the issuer.',
];
